version: "3.8"
services:
  influxdb:
    container_name: metricsdb
    volumes:
      - "/tmp/influxdb:/data"
    image: influxdb
  telegraf:
    container_name: telegraf
    volumes:
      - "$PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    image: telegraf
    depends_on:
      - influxdb
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - "/tmp/grafana:/var/lib/grafana"
    ports:
      - 3000:3000
    depends_on:
      - influxdb
